"""Strategy signal dataclass."""

from dataclasses import dataclass, field
from datetime import datetime, UTC
from typing import Literal


@dataclass
class Signal:
    """A trading signal generated by a strategy."""
    signal_id: str
    strategy_name: str
    symbol: str
    action: Literal["buy", "sell", "hold"]
    confidence: float  # 0.0 to 1.0
    entry_price: float | None = None
    stop_loss: float | None = None
    take_profit: float | None = None
    metadata: dict = field(default_factory=dict)
    timestamp: datetime = field(default_factory=lambda: datetime.now(UTC))

    @classmethod
    def hold(cls, strategy_name: str, symbol: str, confidence: float = 0.0) -> "Signal":
        """Create a hold signal (no action)."""
        return cls(
            signal_id=f"sig_{datetime.now(UTC).timestamp()}",
            strategy_name=strategy_name,
            symbol=symbol,
            action="hold",
            confidence=confidence,
        )